Repository dash-project/dash, pull requests merged in 2018-09, with the labels that each got.

#581 For hostnames longer/equal DART_LOCALITY_HOST_MAX_SIZE dash crashes.
  dart-if/include/dash/dart/if/dart_types.h
  dart-impl/base/src/hwinfo.c
Labels: bug

#570 Performance efficiency improvements for dash::sort
  dart-if/include/dash/dart/if/dart_communication.h
  dart-impl/mpi/include/dash/dart/mpi/dart_communication_priv.h
  dart-impl/mpi/src/dart_communication.c
  dash/include/dash/algorithm/Sort.h
  dash/include/dash/algorithm/internal/Sort-inl.h
Labels: enhancement, performance

#591 Rename dash::accumulate -> dash::reduce
  dash/examples/bench.14.accumulate/main.cpp
  dash/include/dash/Algorithm.h
  dash/include/dash/algorithm/Reduce.h
  dash/include/dash/algorithm/Transform.h
  dash/include/dash/iterator/IteratorTraits.h
  dash/test/algorithm/ReduceTest.cc
  dash/test/algorithm/ReduceTest.h
  dash/test/container/CoarrayTest.cc
Labels: enhancement

#574 DART non-collective global memory allocator
  dart-if/include/dash/dart/if/dart_globmem.h
  dart-if/include/dash/dart/if/dart_types.h
  dart-impl/mpi/include/dash/dart/mpi/dart_mem.h
  dart-impl/mpi/src/dart_allocator.c
  dart-impl/mpi/src/dart_mem.c
  dash/test/dart/DARTMemAllocTest.cc
Labels: enhancement
