Repository dash-project/dash, pull requests merged in 2018-06, with the labels that each got.

#559 Improve Coverage CI
  .circleci/config.yml
  CMakeLists.txt
  dash/scripts/dash-ci-deploy.sh
  dash/scripts/dash-ci.sh
  dash/scripts/dash-test.sh
Labels: support:CI

#558 Use dart_waitall in local-to-global copy
  dart-impl/mpi/src/dart_communication.c
  dart-impl/mpi/src/dart_globmem.c
  dash/include/dash/algorithm/Copy.h
Labels: bug

#562 Provide DART_OP_MINMAX
  dart-if/include/dash/dart/if/dart_types.h
  dart-impl/mpi/include/dash/dart/mpi/dart_communication_priv.h
  dart-impl/mpi/src/dart_communication.c
  dart-impl/mpi/src/dart_initialization.c
  dart-impl/mpi/src/dart_mpi_op.c
  dash/examples/bench.13.allreduce/main.cpp
  dash/test/dart/DARTCollectiveTest.cc
Labels: enhancement, performance

#565 Add MPI include directory to dash-mpicxx
  CMakeExt/GenerateDASHCXX.cmake
Labels: bug
