Repository dash-project/dash, pull requests merged in 2018-04, with the labels that each got.

#519 Smaller fixes to DASH Teams
  dash/include/dash/Init.h
  dash/include/dash/Team.h
  dash/src/Init.cc
  dash/src/Team.cc
  dash/test/algorithm/AccumulateTest.cc
  dash/test/team/TeamLocalityTest.cc
  dash/test/types/AtomicTest.cc
Labels: enhancement

#521 DART Logging: Print timestamps instead of PID
  dart-impl/base/src/logging.c
  dart-impl/mpi/src/dart_communication.c
Labels: enhancement

#525 include gtest using add_subdirectory instead of external project
  CMakeExt/GoogleTest.cmake
  dash/CMakeLists.txt
  dash/test/TestBase.h
Labels: support

#523 Migrate CI to CircleCI v2, massively reducing CI time
  .circleci/config.yml
  circle.yml
  dash/scripts/circleci/collect-artifacts.sh
Labels: support:CI

#526 Disable Locality Tests with OpenMPI2
  .circleci/config.yml
Labels: module:locality, support:CI

#529 Add missing free for basic types ULONGLONG and LONG_DOUBLE
  dart-impl/mpi/src/dart_mpi_types.c
Labels: bug

#530 Bug dart basictypefree
  .circleci/config.yml
  dart-impl/mpi/src/dart_mpi_types.c
Labels: bug
