Repository dash-project/dash, pull requests merged in 2018-03, with the labels that each got.

#493 Fix support for 64bit integer types on 32bit systems
  dart-if/include/dash/dart/if/dart_types.h
  dart-impl/mpi/src/dart_mpi_types.c
  dash/include/dash/Types.h
Labels: bug

#496 Fix setting the C++ standard in the DASH compiler wrapper
  CMakeExt/CompilerFlags.cmake
Labels: bug

#495 Fix move assignment / ctor in Array&Matrix
  dash/include/dash/Array.h
  dash/include/dash/matrix/internal/Matrix-inl.h
  dash/test/container/ArrayTest.cc
Labels: bug

#403 Check OpenMPI version
  CMakeExt/Code/test_compatible_ompi.c
  CMakeExt/Code/test_mpi_support.c
  CMakeExt/HDF5.cmake
  CMakeExt/MPI.cmake
  CMakeLists.txt
  dart-impl/CMakeLists.txt
  dash/include/dash/io/hdf5/StorageDriver.h
Labels: backend:openmpi, backend:openmpi2

#458 Add support for async atomics
  dart-if/include/dash/dart/if/dart_communication.h
  dart-impl/mpi/src/dart_communication.c
  dash/include/dash/Array.h
  dash/include/dash/Atomic.h
  dash/include/dash/GlobAsyncRef.h
  dash/include/dash/GlobRef.h
  dash/include/dash/Matrix.h
  dash/include/dash/Types.h
  dash/include/dash/atomic/GlobAtomicAsyncRef.h
  dash/include/dash/atomic/GlobAtomicRef.h
  dash/include/dash/atomic/Operation.h
  dash/include/dash/matrix/internal/Matrix-inl.h
  dash/include/dash/matrix/internal/MatrixRef-inl.h
  dash/test/iterator/GlobAsyncRefTest.cc
  dash/test/types/AtomicTest.cc
Labels: enhancement, feature

#500 Fix local allocation that are not power of 2
  dart-impl/mpi/src/dart_mem.c
  dash/include/dash/GlobAsyncRef.h
  dash/include/dash/GlobRef.h
  dash/include/dash/atomic/GlobAtomicAsyncRef.h
  dash/include/dash/atomic/GlobAtomicRef.h
  dash/test/dart/DARTMemAllocTest.cc
Labels: bug

#499 GlobRef: Fix compiler warning in conversion operators
  dash/include/dash/GlobAsyncRef.h
  dash/include/dash/GlobRef.h
  dash/include/dash/atomic/GlobAtomicAsyncRef.h
  dash/include/dash/atomic/GlobAtomicRef.h
Labels: enhancement

#497 Remove erroneous DART onesided test
  dash/test/dart/DARTOnesidedTest.cc
Labels: bug

#504 Bug cxx std intel
  CMakeExt/CompilerFlags.cmake
  dart-impl/base/CMakeLists.txt
  dart-impl/mpi/CMakeLists.txt
  dash/CMakeLists.txt
  dash/examples/CMakeLists.txt
  dash/test/CMakeLists.txt
  dash/test/types/GlobIterTest.cc
Labels: bug

#512 Improvements to DASH installation process
  CMakeExt/MPI.cmake
  CMakeLists.txt
  dart-impl/base/CMakeLists.txt
  dart-impl/mpi/CMakeLists.txt
  dash/CMakeLists.txt
  dash/examples/CMakeLists.txt
  dash/scripts/dash-ci-deploy.sh
  dash/scripts/dash-test.sh
  dash/test/CMakeLists.txt
Labels: enhancement, support

#494 Add support for long double in DASH container (incl. Atomic)
  dart-if/include/dash/dart/if/dart_types.h
  dart-impl/mpi/src/dart_mpi_types.c
  dash/include/dash/Types.h
  dash/include/dash/algorithm/Operation.h
  dash/include/dash/atomic/GlobAtomicRef.h
  dash/test/types/AtomicTest.cc
Labels: enhancement

#514 Fix potential segfault in dart_get_handle
  dart-impl/mpi/src/dart_communication.c
Labels: bug

#518 make sure dynamic windows are enabled if shared windows are not disabled
  dart-if/include/dash/dart/if/dart_globmem.h
Labels: enhancement
