Repository dash-project/dash, pull requests merged in 2018-08, with the labels that each got.

#577 CI: Print filename and line in failed assertions
  dash/test/TestBase.h
Labels: enhancement, support:CI

#576 Fix CI test DARTCollectiveTest.CustomReduction
  dash/test/dart/DARTCollectiveTest.cc
Labels: bug, support:CI

#580 fixes issue #579
  dash/include/dash/algorithm/Operation.h
Labels: bug
