Repository dash-project/dash, pull requests merged in 2018-05, with the labels that each got.

#467 Another Try: dash::sort
  dart-impl/mpi/src/dart_communication.c
  dash/include/dash/Algorithm.h
  dash/include/dash/algorithm/Sort.h
  dash/include/dash/algorithm/Transform.h
  dash/include/dash/internal/Logging.h
  dash/src/util/Trace.cc
  dash/test/algorithm/SortTest.cc
  dash/test/algorithm/SortTest.h
Labels: module:algorithms

#534 Feat coverage
  .circleci/config.yml
  CMakeExt/CodeCoverage.cmake
  CMakeLists.txt
  README.md
  build.cov.sh
  dash/CMakeLists.txt
Labels: support:CI

#535 updated all docker images
  .circleci/config.yml
  .codecov.yml
  dash/scripts/docker-testing/mpich/dockerfile
  dash/scripts/docker-testing/openmpi2/dockerfile
  dash/scripts/docker-testing/openmpi2_vg/dockerfile
  dash/scripts/docker-testing/openmpi3/dockerfile
Labels: support:CI

#528 Test CI build also with c++11 (not 14)
  .circleci/config.yml
  CMakeExt/CompilerFlags.cmake
  CMakeExt/GoogleTest.cmake
  dash/include/dash/halo/HaloMatrixWrapper.h
Labels: bug, support:CI

#509 Fix dash::equal Impementation
  dash/include/dash/algorithm/Equal.h
  dash/test/algorithm/EqualTest.cc
  dash/test/algorithm/EqualTest.h
Labels: bug, enhancement

#537 Further Improvements in CI
  .circleci/config.yml
  .travis.yml
  CMakeExt/LAPACK.cmake
  build.cov.sh
Labels: support:CI

#538 Fix index calculations in GlobStaticMem
  dash/include/dash/memory/GlobStaticMem.h
  dash/test/container/MatrixTest.cc
Labels: bug

#541 Use deterministic rngs in debug builds to avoid unwanted coverage
  dash/test/algorithm/SortTest.cc
  dash/test/container/CoarrayTest.cc
Labels: support:CI

#527 Fix Clang Warnings and Rework Const Correctness of GlobRef
  .circleci/config.yml
  CMakeExt/CompilerFlags.cmake
  CMakeExt/MPI.cmake
  dart-impl/mpi/src/dart_globmem.c
  dart-impl/mpi/src/dart_synchronization.c
  dash/CMakeLists.txt
  dash/include/dash/Array.h
  dash/include/dash/Coevent.h
  dash/include/dash/Exception.h
  dash/include/dash/GlobAsyncRef.h
  dash/include/dash/GlobRef.h
  dash/include/dash/Team.h
  dash/include/dash/allocator/EpochSynchronizedAllocator.h
  dash/include/dash/allocator/SymmetricAllocator.h
  dash/include/dash/atomic/GlobAtomicAsyncRef.h
  dash/include/dash/atomic/GlobAtomicRef.h
  dash/include/dash/halo/Halo.h
  dash/include/dash/halo/StencilOperator.h
  dash/include/dash/halo/iterator/StencilIterator.h
  dash/include/dash/iterator/GlobIter.h
  dash/include/dash/iterator/internal/GlobRefBase.h
  dash/include/dash/memory/GlobHeapLocalPtr.h
  dash/include/dash/memory/GlobHeapPtr.h
  dash/include/dash/util/Timer.h
  dash/include/dash/util/internal/TimestampCounterPosix.h
  dash/test/iterator/GlobAsyncRefTest.cc
Labels: enhancement

#552 Bug 551 lapack
  .circleci/config.yml
  CMakeExt/LAPACK.cmake
  dash/scripts/dash-ci.sh
  dash/scripts/docker-testing/minimal/dockerfile
Labels: bug

#555 fixed const correctness issues
  dash/include/dash/halo/HaloMatrixWrapper.h
  dash/include/dash/halo/StencilOperator.h
Labels: bug
